/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 pokemon.gltf 
Author: kuayarts (https://sketchfab.com/kuayarts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-sudowoodo-tree-1f3779a3357340ff8267201572be8b58
Title: Pokemon Sudowoodo - Tree
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pokemon.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.27}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cube_033_2_0.geometry} material={materials.Cube_033} scale={1.048} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pokemon.gltf')
